### ISSUE TITLE
Curl can't write files in dot-leading directories on 21.04

### ISSUE THREAD

**Issue by YuriGor** [woutervb/snap-curl#2]
Hi, on Ubuntu 21.04 I can do this:

```
~/test$ curl https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.xz --output node.test1

  % Total % Received % Xferd Average Speed Time Time Time Current
                                 Dload Upload Total Spent Left Speed
100 21.2M 100 21.2M 0 0 66.2M 0 --:--:-- --:--:-- --:--:-- 66.2M
```

But when I try to do the same in dir with leading dot - it fails:

```
~/.test$ curl https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.xz --output node.test1

% Total % Received % Xferd Average Speed Time Time Time Current
                                 Dload Upload Total Spent Left Speed
  0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0Warning: Failed to create the file node.test: Permission denied
  0 21.2M 0 1085 0 0 20865 0 0:17:45 --:--:-- 0:17:45 20865
curl: (23) Failure writing output to destination
```

I removed curl from snap store and installed one using apt-get, now it works in all cases.

Here is strace for both success and failure
```
~/.test$ strace curl https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.xz --output node.test1
https://pastebin.ubuntu.com/p/fxHdzsgHbw/

~/test$ strace curl https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.xz --output node.test1
https://pastebin.ubuntu.com/p/bxwxMSvjRm/
```

I was redirected here from launchpad :
https://bugs.launchpad.net/snapcraft/+bug/1928185

Previously issue was reported on:
https://github.com/curl/curl/issues/7050

Initially I faced with this bug when I was trying to use node version manager and here is related issue and discussion:
https://github.com/nvm-sh/nvm/issues/2504

**Comment by YuriGor** [comment]
Reply on launchpad about this issue:
>This is not a snapcraft issue per se, a side effect of confinement chosen by the publisher.
// Sergio Schvezov (sergiusens)

**Comment by woutervb** [comment]
Hi @YuriGor,

Thanks for raising this issue. It is indeed due to the default confinement of snaps, and by my knowledge to let a snapped application write anywhere, it will need classic confinement.

An immediate solution for your problem would be to use the following cmdline:
`curl https://nodejs.org/dist/v16.1.0/node-v16.1.0-linux-x64.tar.xz > node1.test1`

This will work, as it's no longer the snapped curl doing the write, but the shell (which has other confinement rules, if any)

Leaving this open, for now as I have contacted @sergiusens to see if there are other options.

**Comment by YuriGor** [comment]
Hi, thank you for reply, in my case I don't use curl directly but it used in NVM tool.
As a workaround (if someone else will be seeking for it) I simply removed snap version of curl and reinstalled it using apt-get:
`sudo apt-get install curl`

**Comment by woutervb** [comment]
@YuriGor just requested classic confinement, that should solve this problem https://forum.snapcraft.io/t/classic-confinement-request-for-curl/24611 especially since all kind of tooling around on the internet will break is the curl snap is installed (and first in the path) as with strict confinement it's limited to writing only in the home directory and I cannot expect the whole of the internet to update their curl instructions.

**Comment by YuriGor** [comment]
>as with strict confinement it's limited to writing only in the home directory

Interesting that I was testing in home directory - it worked for normal directories but failed for dot leading ones also in home.
So probably 'strict' confinement disallows writing into 'hidden' directories even at home?

Another point - it was fine in Ubuntu 20.04, so in 20.04 it was 'classic'? Or not snap a all?

Anyway will need to test it.

**Comment by woutervb** [comment]
strict confinement does not allow any 'external' access by default and each type of access needs to be defined with a plug.

Originally it had access to the home directory (non hidden locations), the ~/.curlrc and network.

But I realized that there are many scripts out in the wild that will assume that curl can write anywhere and will break if the snap takes precedence in the path.

This limitation is depending on the capability of `snapd` to work with security profiles, so most (all) ubuntu versions since 15.04 would have given the same error, but other distributions probably not, since there might be no enforcement there.

The fact that the apt versions did not give you any issues, was as that installed the raw binary no snaps involved at all.

For testing you will have to wait until the request has been approved and you will have to install the snap then via `sudo snap install curl --classic`. No use on testing before this changes has landed.

**Comment by woutervb** [comment]
Classic isn't an option apparently, so there is little I can do about this
